---
- name: adding required iptables rules for web servers
  hosts: web
  user: root

  tasks:
    - name: opening port 80 in iptables
      command: iptables -I INPUT -p TCP --dport 80 -j ACCEPT

    - name: opening port 443 in iptables
      command: iptables -I INPUT -p TCP --dport 443 -j ACCEPT

    - name: save iptables config to persist reboot
      command: service iptables save
